name: workflow

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read


jobs:
  integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Linting repository"

      - name: Run unit tests
        run: echo "Running unit tests"

  
  build-and-push-docker-image:
    name: Continuous Delivery
    needs: integration
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        - run: docker build -t entbappy/deployec2:latest .
        - run: docker push entbappy/deployec2:latest  

  
  pull-and-start-app-on-prod:
    needs: build-and-push-docker-image
    name: Pull Image from docker hub and Start app on EC2
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Hub Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull App Image
        run: sudo docker pull entbappy/deployec2:latest
      - name: Run Docker Image to serve users
        run: sudo docker run -d -p 5000:8080 entbappy/deployec2 
  

     